# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentdetail',
            name='treatmentdetail_assign_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='treatmentdetail',
            name='treatmentdetail_time',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
